### ISSUE TITLE
Future Feature Checklist

### ISSUE THREAD

**Issue by shawn120** [shawn120/Planen-Android#1]
First Priority:

- [ ] Clean codes
- [ ] Fix month view display bug. The refreshing error will jump to the last cached day
- [ ] Try to make the TaskItem back to "type nesting" instead of "type overlapping"

Second Priority:

- [ ] Give deadline task a "complete" checkbox as well
- [ ] Google login and save data into the user calendar
- [ ] Add a trash
- [ ] Add editing function
- [ ] Add a finished tasks view

Later:

- [ ] Dark mode optimize
- [ ] Add more task types: habit check it, shopping list
